substitutions:
  device_name: tof-doesnt-matter
  friendly_name: TOF-DOESNT-MATTER

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  libraries:
    - "pololu/VL53L1X@1.3.1"
  includes:
    - vl53l1x_sensor.h

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  level: DEBUG

api:
  encryption:
    key: "+6lkh+FkWq3HVFh6+NukfmN188wGMQap7sw2RK1p9Gg="

ota:
  - platform: esphome
    password: "48170f28ed94e6fe392d67906b01ff74"

wifi:
  ssid: "BOVENS-MESH"
  password: "605506Jdb"
  power_save_mode: none
  ap:
    ssid: "Lower-Steps Fallback"
    password: "12345678"

captive_portal:

i2c:
  sda: GPIO20
  scl: GPIO21
  scan: true
  frequency: 400kHz

sensor:
  - platform: custom
    lambda: |-
      auto vl53 = new VL53L1XSensor();
      App.register_component(vl53);
      return {vl53};
    sensors:
      - name: "Distance"
        id: distance
        unit_of_measurement: "m"
        accuracy_decimals: 2
        device_class: "distance"
        state_class: "measurement"
        filters:
          - lambda: return x / 1000.0;

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

binary_sensor:
  - platform: template
    id: step_occupied
    name: "Step Occupied"
    lambda: |-
      if (id(distance).has_state()) {
        return id(distance).state < 1.02;
      }
      return false;
    filters:
      - delayed_on: 100ms
      - delayed_off: 500ms

text_sensor:
  - platform: version
    name: "ESPHome Version"

  - platform: wifi_info
    ip_address:
      name: "IP Address"
